language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ceBbFm0AmF7AJxPMMhbsgCZRib5TAvg3N1aSNXGtYKgRxqc29B0rdYoKhJoCxPmoG02dlQd5DzgL6mr4ASFofaeoH/9dYZLVqCFcQCuE79m0dvfGT16PhBYJoHShX1OysB5kPSjtclev6BpFq8kTiujWoc4we/JdvHC3vC9mCO467XuYB0V0rBEsK6jFpfjudDVb4n4Zzf6cvxRgNcFhHMxUV2ANK0Adj8TBUbQI5MQQn1N/BjdOkSaHR2WWILxMQJY05bGNCMxay9BLzjTiMuVS6et88mihRFHZl5o15vRG7a6IO7nnEcXzcpuwPry6DZo+U5oEPqe6uq1BpTNYuW3yatFnNcS7myq4+Kj+gULvux8X3dCGJxjwP8eh+3VH2TL+tot3byU4HINCm93bfOltSH+jdftPrrfDUHVqOEgeccgl53LFxZrVHrPCCv/z+KQTdkL4/Vd49MGYh2cRKZgDEjhHa53oxZjMKiw+IEodJghVXQlzK5RqJw1aj+duqrcBjkO9Ufk+TGsFj9/SVtJqLJpaS/Jql1Kc2LzYalI3dkqWOK0QYZC2B2ngdwDgNquByl89RXOIXuswafw5jFCdptH8KK2WqRhSY3XdsuSiPaX5Qt+iZ6KZa+kPb1iox1FodiIQTRlW+mG9GnfdCITyQpYdpibshKen6GNl9n0=
  on:
    tags: true
    repo: raman325/pypeloton
    python: 3.6
