language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: QfmSKdlyMYuCWxP5bmeeJBIghMSV+UWlwKDMlk3sj1hz7/5HC0UBRQd94HkD1xP7AFTPUpRR1HoxOQrWKm1fFR1OvO3taTceMP2WBam0CY+ptFqaVF1XMu74L9Qx7/O8UAXyKQ+S9MsTr6Ny4nZBpJ6BMIYREeZiAYJojKTygxvQqZueGIDFisZICumff+Q1MNjhBekZ+zCZEIuHJFMqYd72c8G1c+GPgXor3xjt179NwXXq2csjs0WnjMwbP9yxdknMVROgHlDeL3pQcN1Rza74tGDcrb2TlGdKpxyjlUMIlD1uoHY7LAhxQ48puVKTrLx8WENoxMUnu3pK6oX9zrhAE3YRngpqiITsjhwsqCysh8OBGfLFvma4jzTXLldQhbUU4DT/diHUezsGpVXPwsSRKeSatgE8HIsveqAeCMbtKiauSH/xDleMG8HFzYTr8fzskqKYqcWuwLW1ojJ8vjlvXcXBWFQTssyQG53AC2JReUdULFcT9DODPthO9MVWcGN/Bw6n5F+cD5oRHjULbnULg0rn4e93GxAd9UKrKkF4uxw5wKjPS3dZKMg+4fUcA185YLoC41gtvkUIP4yf3JckTUKLqjOVvX2S6hKCn+MDUKux7Gw8GDnmaeAVKHTGV8Rpxf25uiYovDfy+ZpAiPgzX8zahQ0IlDsOTp+EbOk=
  on:
    tags: true
    repo: raman325/pypeloton
    python: 3.6
