language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: e3A9KIXQgu5SKvjSMu6juC5iInlB5mlYY141TnFD5YNBYYu2g2YF48r5+bH/gPO9/zjpngKSQXyYLo4Kc8hnLbJTd6EHfM/vcq5WXmWxzAhAyYKDHyoNy+NqTxHqSWtS94dEbeVzJ9MJRSPQ3R0niNPEJayPDgpbvTkWQKgnqf7IOhatlLV199apQyjFHkqP3EOaFupCKkHqUdejXsdr7Ov7V1rTIMPYB04SzD133Xp/o5xN4anz2n1oAusaSFsLREuG9dbosl6I8AiYFyWgNcM1YHNVD4n6+5ZkbkVzWP7UbPlH79RdjEgBO++xkI0VW9l/5LQaf7/pYP77OXRTgWMIXjWmGe2IEhbidLjZCpap1+InvpnuS1LXmzxVXzw8c1vPyxk3UGILOLJFWTduKk3gouayuQzOG862f0Ng9v4X1SiJEJujqSPrwEEMjbVfRjHjqxco5M6K/4fIcCoZPvBovUHcLTErOefeRSWf6vYg4qZWAmVAZBu7SH9DU3jlSFTq6bjQCTNlhs9Llhlk4jCMTvPUF/t8Xg8B67zl8GBmlr3JPC8UpqZKiwKv3SIiCkDu0kRJqd4pDDL0rIsweEKdsg/CKmo1PE9OsGAZY7NT5kieqfG4c3B2fMqPbQAyeSs9hglScvyGl735lF8RA2cl8iO/hfZPyrP518KK0x8=
  on:
    tags: true
    repo: raman325/pypeloton
    python: 3.6
